version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    labels: []
    open-pull-requests-limit: 10
    ignored_updates:
      - match:
          dependency_name: "*@storybook/"
          version_requirement: "6.x"
